### PR TITLE
fix json parser to not break for link command

### LINKED ISSUE #151: Fix parser error in link command

### PR DESCRIPTION
**Pull request by lavanyagarg112**
Fixed the jsonadaptedperson to parse and store the data for link correctly

Fixes #151

### CODE REVIEW

File: src/main/java/seedu/address/storage/JsonAdaptedPerson.java [hunk 1]
```diff
@@ -47,8 +47,8 @@ public JsonAdaptedPerson(@JsonProperty("name") String name, @JsonProperty("nric"
             @JsonProperty("phone") String phone, @JsonProperty("email") String email,
             @JsonProperty("address") String address,
             @JsonProperty("tags") List<JsonAdaptedTag> tags, @JsonProperty("roles") List<JsonAdaptedRole> roles,
-            @JsonProperty("caregivers") List<Nric> caregivers,
-            @JsonProperty("patients") List<Nric> patients,
+            @JsonProperty("caregivers") List<String> caregivers,
+            @JsonProperty("patients") List<String> patients,
```
Comment (pradyuprasad) [inline src/main/java/seedu/address/storage/JsonAdaptedPerson.java:51]: Good work spotting the bug!

**Review by pradyuprasad — APPROVED** [review]
LGTM

File: src/main/java/seedu/address/storage/JsonAdaptedPerson.java (hunk 1 above)
Comment (lavanyagarg112) [reply src/main/java/seedu/address/storage/JsonAdaptedPerson.java:51]: thanks!
